### ISSUE TITLE
Rendered map disables html5 video on Android?

### ISSUE THREAD

**Issue by heks** [wf9a5m75/phonegap-googlemaps-plugin#407]
So this is a very odd behavior but in my app enabling the Google Map stops my html5 video from playing on Android devices (audio only plays). For example, I disabled the map by removing SHA1 key from the Google Developer Console and my videos play fine, but as soon as I add back to SHA1 key none of my videos play but my map renders fine. Anyone else getting this?

**Comment by wf9a5m75** [comment]
I have no idea, but this maybe related.
Google Maps Android API v2 uses OpenGL internally.
Disabling the map, Google Map does not generate the map tile layer probably.
That's why the video is displayed fine.

This plugin does not block the behavior at all. Just placing the map layer under the browser view.
Please ask to Google.
https://code.google.com/p/gmaps-api-issues/issues/list?can=2&q=apitype:Android2%20type:Defect&sort=-stars&colspec=ID%20Type%20Status%20Introduced%20Fixed%20Summary%20Internal%20Stars
