### ISSUE TITLE
Make location text multilang

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#420]
Hi Masashi,

is there any way we can make the location text multilanguage?

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/plugin.xml#L164-L170

Actually it's always english. We should include language-files. I could translate German, English, French.
I'm sure there are other people that could help to translate in 30 other languages. As this textparts are that short, we could also you google translate for them.

**Comment by wf9a5m75** [comment]
Memo for myself.
http://qiita.com/hshimo/items/d6a7dd2ff2f2e5c266e7

**Comment by sangariv** [comment]
HI,
is ther way to draw path for the source and destination.

**Comment by wf9a5m75** [comment]
@sangariv Please don't merge your issue with others.

**Comment by sangariv** [comment]
ok can u plesase answer in my issue

**Comment by wf9a5m75** [comment]
Sorry for late response. I'm on business trip.

**Comment by wf9a5m75** [comment]
Xcode supports localization for Info.plist files.
In order to use that, the plugin create a new file under the `Resources/(language).proj/InfoPlist.strings`.

However, Cordova will be error if there is an Info.plist file if there is a file that is the same filename.
It means if another plugin creates an InfoPlist.strings file before this plugin installing, you can not install the map plugin.

The difficult thing is that the message for NSLocationWhenInUseUsageDescription is not able to change from code.

**Comment by wf9a5m75** [comment]
And Apache ant can not merge Strings into not XML format file.

**Comment by Hirbod** [comment]
How does other plugins manage this? Like InAppBrowser? I guess they use native elements..

**Comment by wf9a5m75** [comment]
InAppBrowser does not use InfoPlist file.

However NSLocationWhenInUseUsageDescription, NSLocationAlwaysUsageDescription, and NSLocationAlwaysUsageDescription have to located in Info.plist.

**Comment by wf9a5m75** [comment]
I googled for a while, but there is no perfect solution currently.

I think Cordova should implement the merge feature for any text file, or
Cordova should support multiple languages for Info.plist. (That's not this plugin's role)

Please make an issue at Apache Cordova project.
https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel

I close this issue at once with the `knowledge issue` label.
If you have a new update, re-open this issue.
