### ISSUE TITLE
Cordova Android 3.7.1 problem

### ISSUE THREAD

**Issue by Hirbod** [wf9a5m75/phonegap-googlemaps-plugin#421]
Hi Masashi,

Android-Cordova 3.7.1 is out a few days and target API-Level 21 by default.
(Android 5)

![bildschirmfoto 2015-02-28 um 06 50 58](https://cloud.githubusercontent.com/assets/504909/6425060/60c378f2-bf16-11e4-9553-49d90196ed60.png)

This cause a problem with your HTTP-Plugin

![bildschirmfoto 2015-02-28 um 06 51 26](https://cloud.githubusercontent.com/assets/504909/6425062/69477456-bf16-11e4-918a-35149153288d.png)

If I set to 4.4.2 (Level 19), compiling works, but not with 21.

Can we remove your http plugin complete? I think it is a big overhead to implement a new http dependencie. But please never rely on OkHttp as it will be removed in Cordova 4.0 and also causes SSL crashes.

Why do you even use R9Http ? Just for looking for an update?

**Comment by wf9a5m75** [comment]
I want to separate the code of HTTP part, because I want to update it if there is any problem instead of waiting the map plugin update.
And I don't want to write the code for HTTP communication multiple times.
Further more, for supporting Direction API, I will use it.

So I don't agree with your idea.

And R9Http is in iOS part, not related to Android.

If you find a problem, please send to pull request to https://github.com/wf9a5m75/phonegap-http-request

**Comment by Hirbod** [comment]
Ok, thats fine. But still, there is this 5.0.1 bug right now.

**Comment by wf9a5m75** [comment]
I think Android 5.0.1 is not related. The problem has occurred since before.

This line is problem point.
https://github.com/wf9a5m75/phonegap-http-request/blob/master/src/android/plugin/http/request/HttpRequest.java#L55

I wrote like this originally.
https://github.com/wf9a5m75/phonegap-http-request/commit/bc54d4aac50d974f36f6f63c28ef74c443f0ca4c#diff-13508e738c24669203ca2f5d2172ebed

But AppGyber, AppBuilder, something like that, can not accept this idea.
That's why I changed to the current code.
Because JSON should have only string keys.
However your error.

If you find out a better solution, please send pull request.
I'm on business trip until two days later, so I can not debug it.

**Comment by Hirbod** [comment]
It's ok. Seems like eclipse is just yelling. I could build it with Cordova-CLI

**Comment by wf9a5m75** [comment]
For your information, NSMutableURLRequest can not follow the redirect header.
And R9HTTPRequest communicates with the server in asynchronous.

The problem is that R9HTTPRequest handles the response data as String.
In order to use R9HTTPRequest for marker, I need to modify the code.

**Comment by Hirbod** [comment]
Hi Masashi, as said, Cordova Andorid 3.7.1 won't work anymore with your plugin:

```
-compile:
    [javac] Compiling 146 source files to /Users/Hirbod/Desktop/appdev/Nachbarschaft/platforms/android/ant-build/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /Users/Hirbod/Desktop/appdev/Nachbarschaft/platforms/android/src/plugin/http/request/HttpRequest.java:56: error: incompatible types: Iterator<String> cannot be converted to Iterator<Object>
    [javac]         Iterator<Object> iterator = params.keys();
    [javac]                                                ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 3 warnings
```

It fails because of HttpRequest.java

If I specify the target-level to API 19, evertyhing is fine, if I set to API 21, it break.

**Comment by wf9a5m75** [comment]
You use old code.
https://github.com/wf9a5m75/phonegap-http-request/blob/master/src/android/plugin/http/request/HttpRequest.java#L55

**Comment by Hirbod** [comment]
Ok, I fixed it by myself, but I will remove your plugin now and reinstall the #test branch again

**Comment by Hirbod** [comment]
Ok, bug is fixed!
