### ISSUE TITLE
zoom buttons are not shown completely in Android Lollipop app

### ISSUE THREAD

**Issue by siran** [wf9a5m75/phonegap-googlemaps-plugin#439]
zoom buttons are not shown completely in Android Lollipop app

![screenshot_2015-03-12-23-46-41](https://cloud.githubusercontent.com/assets/180129/6632835/6cb80f22-c913-11e4-9ab8-f361da7d9ae5.png)

**Comment by wf9a5m75** [comment]
It seems you set div as full screen.

**Comment by wf9a5m75** [comment]
And call `map.refreshLayout()`

**Comment by wf9a5m75** [comment]
I think the title bar is the problem that occurs this issue.
Because if you set the map div as full screen (such as width: 100%; height: 100%), the Google Maps Logo should appear at the bottom of the zoom button.
But no logo in your picture.

In this case, the title bar push away the map div out side the body tag.

If you don't understand this description, try to use Chrome Inspection, then check the size.
https://developer.chrome.com/devtools/docs/remote-debugging

**Comment by wf9a5m75** [comment]
![issue_439](https://cloud.githubusercontent.com/assets/167831/6643444/828105ce-c969-11e4-8886-0748f29b9337.png)

**Comment by wf9a5m75** [comment]
And hiding the Google Maps Logo is prohibited. It's against the Google Maps Terms of service.
You need to adjust the div size.

**Comment by siran** [comment]
you were right, it was the height of the header...

thank you!
