### ISSUE TITLE
Crosswalk throws exception in HTMLColor2RGBA

### ISSUE THREAD

**Issue by trancee** [wf9a5m75/phonegap-googlemaps-plugin#441]
I just tried out my Cordova app using Crosswalk and when I want to load the Google Maps plugin, it throws this error:

<code>The browser does not support the getPropertyCSSValue method!
file:///android_asset/www/plugins/plugin.google.maps/www/googlemaps-cdv-plugin.js
</code>

It works fine without Crosswalk, but I need it to be working for Crosswalk as well. I am using crosswalk-
cordova-11.40.277.7-arm for this.

**Comment by wf9a5m75** [comment]
I think this plugin does not work on Crosswalk (at least I can not).
Because the background transparent does not work properly.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/302
https://crosswalk-project.org/jira/browse/XWALK-3742

Anyway, you can pass one of the color format:
`transparent`, `rgb(r,g,b)`, `rgba(r,g,b,a)`, `hsla(h,s,l,a)`, `hsl(h, s, l)`, or  `color names`(such as red, or white).

If you specify any above color but `color names`, the plugin does not use `getPropertyCSSValue` method.
So try to use `rgb()` instead of `color names`
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/www/googlemaps-cdv-plugin.js#L1822-L1878

**Comment by trancee** [comment]
OK, after I changed the background to something else than <code>color names</code> it does not show that error anymore.

Unfortunately, the map does still not show up in Crosswalk.

Thanks for reporting the issue to the Crosswalk project. I will close this issue and open a new one with that issue number from Crosswalk to track the status.

**Comment by Hirbod** [comment]
Thanks trancee. You don't to open a new issues as there are still two issues and crosswalk has as high priority to us

**Comment by trancee** [comment]
Yes, I just noticed that there is already another issue open. I will follow that one.
