### ISSUE TITLE
setCenter don't work in ios

### ISSUE THREAD

**Issue by tsecheng** [wf9a5m75/phonegap-googlemaps-plugin#444]
in android: it is ok
```
const latlng = new plugin.google.maps.LatLng(lat, lng);
map.setCenter(latlng);
map.setZoom(17);	
```

but don't work in ios, my xcode is 6.2, test device iphone 6 plus
```
const latlng = new plugin.google.maps.LatLng(lat, lng);
map.setOptions({
    	'camera':{
    		'latLng':latlng,
    		'zoom':17
    	}
 });     
```
i must use setOptions to work, yes android work with setOptions too!

**Comment by wf9a5m75** [comment]
I'll check this later.

**Comment by wf9a5m75** [comment]
You shouldn't use map.setCenter() and map.setZoom() at the same time.

`map.setZoom()` cancels the previous camera action, it means `map.setCenter()` is canceled because you called `map.setZoom()`

If you set the camera action with two parameters, you should use `map.animateCamera()` or `map.moveCamera()`.

This is not bug.

**Comment by tsecheng** [comment]
thank you for your answer!
my concern is android platform work, but ios don't.
android and ios don't the same behavior.
